### ISSUE TITLE
iobroker.starline cannot connect to server

### ISSUE THREAD

**Issue by Palisade8** [instalator/ioBroker.starline#27]
Version 1.0.0 in /opt/iobroker/node_modules/iobroker.starline, node: v12.19.0, js-controller: 3.1.6 run on Debian 10.6
ERROR failed to get PHPSESSID

Mobile application is working, password was changed twice.

**Comment by instalator** [comment]
fixed

**Comment by muehle79** [comment]
Same issue here. What was the solution?

**Comment by instalator** [comment]
The problem is fixed in the new version

**Comment by muehle79** [comment]
Is there a release date for the new version?

**Comment by instalator** [comment]
Version 1.1.3

**Comment by Palisade8** [comment]
It's Greate. it' working.
But there is no new version on officical page of ioBroker? you need to update from GitHub repositories

**Comment by muehle79** [comment]
I still have the same probleme......
ERROR failed to get PHPSESSID

Is there something more i have to do? I am now on 1.1.3 adapter
